# Config file for the Air live reloader



[log]
level = "debug"
output = "stdout"
format = "terminal"

[color]
main = "cyan"
watcher = "magenta"
runner = "yellow"
error = "red"

[build]
cmd = "templ generate && go build -o ./tmp/main.exe ./main.go"
args_bin = []
bin = "./tmp/main.exe"
full_bin = ""
delay = 1000
exclude_dir = ["assets", "vendor"]
exclude_file = []
exclude_regex = ["_test\\.go", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "templ", "js", "css"]
include_file = []
kill_delays = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
step_on_error = false
force_rebuild = false

[misc]
clean_on_exit = true
